### ISSUE TITLE
license and performance improvement

### ISSUE THREAD

**Issue by cigolpl** [spencermountain/wikipedia-to-mongodb#7]
hi, thanks for doing that script! It is extremely simple and works perfect with small xml dataset i.e. af wikipedia but with the biggest one it is quite slow and one error stops script execution. 

I guess the bottleneck is `wikipedia.parse` because it is run synchronously on one CPU and it is blocking. Once I commented `wikipedia.parse` it speed up even to x10 on my computer.

My solution would be to use some job queue for calculating `wikipedia.parse` and saving to mongodb on all CPU's. 

I would like to make such a improvement and make PR for your review but please define license for your script before.

**Comment by spencermountain** [comment]
hey Mateusz! thanks. 
what are you writing into the db, instead of wikipedia.parse? the raw wikiscript stuff?
interesting point. wikipedia.parse is just a shit-tonne of regular-expressions, so is surely slow, but I wouldn't know how to make it async without some fancy queue library - is that your idea?
i'd be interested in this, for sure!
if you didn't want the results of wikipedia.parse(), we could just add a flag to turn that off, that's an easy one.
let me know,
cheers

**Comment by cigolpl** [comment]
Hi Spencer,
`wikipedia.parse` works great and provide good results except being quite slow. I don't know if that can be faster and probably it is best available solution right now. 

My thought was using job queue library like https://github.com/Automattic/kue (node.js + redis) to make these calculations in separate workers then we could maximize usage of all CPU's.

I have assumption it will be much faster and more reliable with kue but I can be wrong too. I will make tests anyway and propose PR for review if that successful.

Your API is very simple so I would keep it as it is and make queue and redis optional.
Let me know what do you think about that idea

**Comment by spencermountain** [comment]
:+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: 
sounds great, good luck!

**Comment by cigolpl** [comment]
@spencermountain #8 is ready for review!
